
# Generated by CodiumAI
from modelo import Modelo
import numpy as np


import pytest

class TestEncontrarPosicionLibre:

    # should return the index of the first element in 'pacientes_actuales' that is equal to 0
    def test_return_index_of_first_element_equal_to_0(self):
        modelo = Modelo(10, 2, 100)
        modelo.pacientes_actuales = np.array([1, 0, 2, 0, 3])
        assert modelo.encontrar_posicion_libre() == 1

    # should raise an IndexError if there are no elements equal to 0 in 'pacientes_actuales'
    def test_raise_index_error_if_no_elements_equal_to_0(self):
        modelo = Modelo(10, 2, 100)
        modelo.pacientes_actuales = np.array([1, 2, 3])
        with pytest.raises(IndexError):
            modelo.encontrar_posicion_libre()

